import turtle

turtle.forward(1)
turtle.left(90)
turtle.forward(1)
turtle.left(90)
turtle.forward(2)
turtle.left(90)
turtle.forward(3)
turtle.left(90)
turtle.forward(5)
turtle.left(90)
turtle.forward(13)
turtle.left(90)
turtle.forward(21)
turtle.left(90)
turtle.forward(34)
turtle.left(90)
turtle.forward(55)
turtle.left(90)
turtle.forward(89)

turtle.exitonclick()